# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160609_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='name',
            new_name='nome',
        ),
    ]
