# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160609_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indice',
            old_name='municipio',
            new_name='geocode',
        ),
    ]
